version: "3.6"
services:
  discounts:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-discounts
    volumes:
    - ./discounts:/go/api
    - ./testdata:/go/testdata
    stdin_open: true
    tty: true
    ports:
    - 8080:8080

  products:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-products
    command: make start
    env_file: 
      ./products/.env
    volumes:
    - ./products:/srv
    - ./testdata:/testdata
    - ./discounts/proto:/dist/proto
    stdin_open: true
    tty: true
    ports:
    - 8081:8081
  
  mongodb:
    image: mongo:4
    logging:
      driver: none
    environment:
    - AUTH=no
    ports:
    - 27017:27017
