version: "3.6"
services:
  discounts:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-discounts
    volumes:
    - ./discounts:/go/api
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:4
    logging:
      driver: none
    environment:
    - AUTH=no
    ports:
    - 27017:27017
