FROM golang:1.16.3

RUN apt update && \
    apt install -y protobuf-compiler

ENV GO111MODULE on

RUN go get google.golang.org/protobuf/cmd/protoc-gen-go \
    google.golang.org/grpc/cmd/protoc-gen-go-grpc \
    github.com/onsi/ginkgo/ginkgo

WORKDIR /go/api