FROM python:3.8-slim-buster as base

RUN apt update && \
    apt install -y make protobuf-compiler

RUN \
    pip install --upgrade pip; \
    pip install pipenv;

COPY ./products/Pipfile /srv/Pipfile
COPY ./products/Pipfile.lock /srv/Pipfile.lock
COPY ./products/Makefile /srv/Makefile

WORKDIR /srv

RUN make dep