// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DiscountCalculatorClient is the client API for DiscountCalculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscountCalculatorClient interface {
	Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error)
}

type discountCalculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscountCalculatorClient(cc grpc.ClientConnInterface) DiscountCalculatorClient {
	return &discountCalculatorClient{cc}
}

func (c *discountCalculatorClient) Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error) {
	out := new(CalculateResponse)
	err := c.cc.Invoke(ctx, "/discounts.DiscountCalculator/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscountCalculatorServer is the server API for DiscountCalculator service.
// All implementations must embed UnimplementedDiscountCalculatorServer
// for forward compatibility
type DiscountCalculatorServer interface {
	Calculate(context.Context, *CalculateRequest) (*CalculateResponse, error)
	mustEmbedUnimplementedDiscountCalculatorServer()
}

// UnimplementedDiscountCalculatorServer must be embedded to have forward compatible implementations.
type UnimplementedDiscountCalculatorServer struct {
}

func (UnimplementedDiscountCalculatorServer) Calculate(context.Context, *CalculateRequest) (*CalculateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedDiscountCalculatorServer) mustEmbedUnimplementedDiscountCalculatorServer() {}

// UnsafeDiscountCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscountCalculatorServer will
// result in compilation errors.
type UnsafeDiscountCalculatorServer interface {
	mustEmbedUnimplementedDiscountCalculatorServer()
}

func RegisterDiscountCalculatorServer(s grpc.ServiceRegistrar, srv DiscountCalculatorServer) {
	s.RegisterService(&DiscountCalculator_ServiceDesc, srv)
}

func _DiscountCalculator_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountCalculatorServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discounts.DiscountCalculator/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountCalculatorServer).Calculate(ctx, req.(*CalculateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscountCalculator_ServiceDesc is the grpc.ServiceDesc for DiscountCalculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscountCalculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discounts.DiscountCalculator",
	HandlerType: (*DiscountCalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _DiscountCalculator_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discounts.proto",
}
